### ISSUE TITLE
Finance API

### ISSUE THREAD

**Issue by javathunderman** [Emposoft/EdFinance#1]
Useful links for my purposes: http://www.androidauthority.com/use-remote-web-api-within-android-app-617869/

+ http://dev.markitondemand.com/MODApis/#stockquote

**Comment by Taloz** [comment]
Currently we have the [Stock Quote JSON class](../tree/master/app/src/main/java/com/emposoft/edfinance/data/json/StockQuote.java) done ([API Example](http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol=AAPL)) for Markit On Demand.

Serialization Todo:
 - Company Lookup API ([API Example](http://dev.markitondemand.com/MODApis/Api/v2/Lookup/json?input=NFLX))
 - Interactive Chart API ([API Example](http://dev.markitondemand.com/MODApis/Api/v2/InteractiveChart/json?parameters=%7B%22Normalized%22%3Afalse%2C%22NumberOfDays%22%3A365%2C%22DataPeriod%22%3A%22Day%22%2C%22Elements%22%3A%5B%7B%22Symbol%22%3A%22AAPL%22%2C%22Type%22%3A%22price%22%2C%22Params%22%3A%5B%22c%22%5D%7D%5D%7D))
 - Error Message ([API Example](http://dev.markitondemand.com/MODApis/Api/v2/Quote/json))

I'll hopefully finish the above JSON classes within this week (the interactive chart API might be a nightmare to do).

**Comment by javathunderman** [comment]
@Taloz sync up on slack scheduled as discussed! Should be able to get things moving faster.

**Comment by Taloz** [comment]
As of commit 17561893e60c93f872f8ee4209c156cc67238b90, Company Lookup and Error Message JSON classes have been added. The only thing left to do is the Interactive Chart.

**Comment by Taloz** [comment]
Apparently Markit on Demand's Stock Quote API isn't able to fetch Dow Jones or NASDAQ due to it only showing stocks from the BATS exchange.

**Comment by Taloz** [comment]
We could use [YQL](https://developer.yahoo.com/yql/) (Yahoo! Query Language). 

Open the link and type `select * from yahoo.finance.quotes where symbol="GOOG"` and it will return Google's stock. Apparently you can get the indexes there but I can't get ^DJI or INDU to work for Dow Jones (haven't tested anything else).

**Comment by javathunderman** [comment]
working on this...

**Comment by Taloz** [comment]
Which market API should we go with? (or are we still deciding?)

**Comment by javathunderman** [comment]
Yahooooooooo it is

**Comment by Taloz** [comment]
For NASDAQ we can use YQL to fetch it (^NDX), however the Dow Jones appears to be blocked, so we can calculate it (see: https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average#Calculation) in the application

**Comment by javathunderman** [comment]
I'll check if there's a less horrible API.

**Comment by Taloz** [comment]
Base YQL JSON classes have been implemented as of commit 3ecc303a167d1477fa5417ac26fadc6ffbb5ffc8

**Comment by Taloz** [comment]
We should now be able to parse results from Yahoo Finance via YQL. It's just a matter of adding the gson library and downloading the URL using DownloadTask.

**Comment by javathunderman** [comment]
hoorah!

**Comment by Taloz** [comment]
Yay, this is finished as of commit 62cd80d26ba44d9c33b9cc1ac015f7159a7425c1. Minor optimizations will be done for the YQL API but for now it works perfectly.

**Comment by javathunderman** [comment]
hooray!
